# XDG
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"

# Editors
export EDITOR='nvim'
export SUDO_EDITOR="nvim"
export VISUAL='nvim'
export KUBE_EDITOR='nvim'
export SQITCH_EDITOR='nvim'

# ZSH
export ZSH_CONFIG="${HOME}/.config/zsh"
export ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
export CARGO_HOME="$HOME/.cargo"
export NVM_DIR="${HOME}/.nvm"
export GOPATH="$HOME/.local"

# Language
export PIPENV_HIDE_EMOJIS=1

# Path
typeset -U path PATH
path=(
  $HOME/.local/bin/private
  $HOME/.local/bin/public
  $HOME/bin
  /usr/local/bin
  /usr/bin
  /opt/local/bin
)

export PATH

