# Enable complex autocompletion
autoload -Uz compinit
compinit

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000

ZSH_CONFIG="${HOME}/.config/zsh"
ZSH_COMPDUMP=~/.cache/.zcompdump-$HOST
DISABLE_AUTO_TITLE=true

fpath+=~/.zfunc

# Enable ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > "/tmp/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "/tmp/ssh-agent.env" > /dev/null
fi

source "$ZSH_CONFIG/aliases.zsh"
source "$ZSH_CONFIG/antidote/antidote.zsh"
antidote load "$ZSH_CONFIG/zsh_plugins.txt"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source <(kubectl completion zsh)

# Enable emacs mode to run properly shortcuts licke Cntrol+A, etec
bindkey -e
eval "$(starship init zsh)"
