# Enable complex autocompletion
autoload -Uz compinit
compinit

export HISTFILE=~/.config/zsh/histfile
export HISTSIZE=100000
export SAVEHIST=100000

setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.

fpath+=~/.zfunc

# Enable ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > "/tmp/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "/tmp/ssh-agent.env" > /dev/null
fi

source "$ZSH_CONFIG/antidote/antidote.zsh"
antidote load "$ZSH_CONFIG/zsh_plugins.txt"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source <(kubectl completion zsh)

# Enable emacs mode to run properly shortcuts licke Cntrol+A, etec
bindkey -e
eval "$(starship init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# opencode
export PATH=/home/jtorrex/.opencode/bin:$PATH

# Aliases
source "$ZSH_CONFIG/aliases.zsh"
