# Completions
fpath+=("$XDG_DATA_HOME/zsh/completions")
autoload -Uz compinit
if [[ ! -f $XDG_CACHE_HOME/zsh/zcompdump ]]; then
  compinit -d "$XDG_CACHE_HOME/zsh/zcompdump"
else
  compinit -C -d "$XDG_CACHE_HOME/zsh/zcompdump"
fi

# History
setopt SHARE_HISTORY
export HISTFILE=~/.config/zsh/histfile
export HISTSIZE=100000
export SAVEHIST=100000
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.

# Plugins bundled
# Generate with: antidote bundle < ~/.config/zsh/zsh_plugins > ~/.config/zsh/zsh_plugins.zsh
source "$ZSH_CONFIG/zsh_plugins.zsh"

# FZF
[[ $- == *i* ]] && [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# Keymap / prompt
bindkey -e
eval "$(starship init zsh)"

# Aliases
source "$ZSH_CONFIG/aliases.zsh"

# NVM lazy load (only if not already loaded by oh-my-zsh)
if ! type nvm &>/dev/null; then
  load-nvm() {
    unset -f node npm npx
    [[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
  }
  node() { load-nvm; node "$@" }
  npm()  { load-nvm; npm "$@" }
  npx()  { load-nvm; npx "$@" }
fi

# Terraform completion
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# ctx shell hook
eval "$(ctx shell-hook zsh)"
