##### Terminal & Environment #####
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-kitty:Tc"
set -as terminal-features ",xterm*:RGB"
set -g allow-passthrough on
set -ga update-environment "TERM TERM_PROGRAM"
set -gw xterm-keys on

##### Behavior #####
set -g prefix C-a
set -s escape-time 0
set -sg repeat-time 600

#### Monitoring & Notifications #####
set -s focus-events on
set -g bell-action none
set -g visual-bell off
set -g visual-activity off
set -g visual-silence off

##### Encoding #####
set -q -g utf8 on
set -q -g status-utf8 on

##### Window Management ######
set -g automatic-rename off
set -g base-index 1
set -g pane-base-index 1
set -g set-titles on
set -g display-panes-time 200
set -g display-time 300
set -g history-limit 10000

##### Keybinds #####
unbind C-b
bind - split-window -v
bind _ split-window -h
unbind '"'
unbind %
bind e new-window -n "~/.config/tmux/tmux.conf" "sh -c '\${EDITOR:-vim} ~/.config/tmux/tmux.conf && tmux source ~/.config/tmux/tmux.conf && tmux display \"~/.config/tmux/tmux.conf sourced\"'"
bind r source-file ~/.config/tmux/tmux.conf
bind q kill-pane
bind Q kill-window

#### Swap & Resize Panes ####
bind > swap-pane -D
bind < swap-pane -U
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Navigation
bind-key -n M-C-l switch-client -p
bind-key -n M-C-h switch-client -n
bind-key -n M-C-k select-window -p
bind-key -n M-C-j select-window -n
bind-key -n M-k select-pane -t :.-
bind-key -n M-j select-pane -t :.+
bind-key -n M-Tab next-window
bind-key -n M-S-Tab previous-window

#### Mouse ####
set -g mouse on

#### Copy Mode ####
tmux_conf_copy_to_os_clipboard=true
bind Enter copy-mode # enter copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind Escape copy-mode

##### Status Bar #####
tmux_conf_24b_colour=true
set-option -g status "on"
set -g status-position bottom
set -g status-justify left
set -g status-interval 10
set -g status-right-length 50
set -g status-right-style default
set -g status-left-length 15
set -g status-left-style default
set -g status-left " ❐ [#S] "
set -g status-fg black
set -g status-bg green
set -g status-right "| %a %d-%m-%y | %H:%M "
set -g window-status-current-style fg=black
set -g window-status-current-style bg=red
set-window-option -g clock-mode-colour colour109 #blue
