theme = "plain"
icons = "awesome"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "load"
interval = 1
format = "{1m}/{5m}/{15m}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{icon} {used}/{total}" 
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "echo '\uf0ac ' `curl ifconfig.me`" # assumes fontawesome icons
interval = 60

[[block]]
block = "net"
format = "{ssid}"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
interval = "once"
#[[block]]
#block = "battery"
#if_command = "test -e /sys/class/power_supply/BAT0"
