[theme]
theme = "plain"

[icons]
icons = "awesome6"

[[block]]
block = "load"
interval = 1
format = "$icon $1m.eng(w:4)"

[[block]]
block = "memory"
format = "$icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 5
warning_mem = 80
critical_mem = 90

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 20.0
format = "$icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "keyboard_layout"
driver = "localebus"
interval = 15

[[block]]
block = "time"
interval = 5
[block.format]
full = "$icon $timestamp.datetime(f:'%Y/%m/%d %a %R %Z', l:en_US) "
short = "$icon $timestamp.datetime(f:%R) "

[[block]]
block = "custom"
command = "echo '\uf0ac' `curl ifconfig.me`" # assumes fontawesome icons
interval = 60

[[block]]
block = "net"
format = "$icon {$signal_strength $ssid $frequency|}$device "
