require("core.options")
require("core.plugins")
require("core.colorscheme")
require("core.lualine")
require("core.keymaps")
require("core.nvim-tree")
require("core.telekasten")
require("core.telescope")
-- require("core.markdownpreview")
require("core.indent-blankline")
require("core.treesitter")
require("core.lsp")
require("core.completions")
