# ---- Global ----
add_newline = false
command_timeout = 500
scan_timeout = 100
format = "$directory$git_branch$git_status$python$conda$docker_context$character"
right_format = "$cmd_duration"

# ---- Module Configuration ----
# ---- Directory ----
[directory]
truncation_length = 3
truncate_to_repo = false # truncates directory to root folder if in github repo
style = "bold italic blue"
read_only = " "  # Unicode character for lock symbol

# ---- Character ----
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

# ---- Command Duration ----
[cmd_duration]
min_time = 500 # Show duration if command takes more than 500ms
style = "dimmed white"

# ---- Git ----
[git_branch]
symbol = " "
style = "bold yellow"
truncation_length = 15
only_attached = true

[git_status]
disabled = false
format = '([$all_status$ahead_behind]($style))'
style = "dimmed yellow"

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '
detect_folders = [".git"]

# ---- Python ----
[python]
disabled = false
symbol = " "
pyenv_version_name = true
detect_folders = [".venv", "venv", "env"]
#format = "[$symbol$version]($style) "
format = ' [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
detect_extensions = ["py"]
version_format = "v${raw}"

# ---- Docker ----
[docker_context]
symbol = "🐳 "
format = "[$symbol$context]($style) "
disabled = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true
